# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: dns-lookup

# Remember to install project dependencies to register the provider plugin.
# $ npm install
provider:
  name: openwhisk
  runtime: python:3
  ignore_certs: true

functions:
  resolve_a:
    handler: handler.resolve_a
    annotations:
      web-export: true
    events:
      - http:
        path: dns/resolve/a
        method: get
        resp: json

  resolve_cname:
    handler: handler.resolve_cname
    annotations:
      web-export: true
    events:
      - http:
        path: dns/resolve/cname
        method: get
        resp: json

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk
  - serverless-python-requirements
	
custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt
    useDownloadCache: false
    useStaticCache: false